name: Maven Package

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract version from branch name
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2

#      - name: Build with Maven
#        run: mvn -B package --file pom.xml -Drevision=${{ env.RELEASE_VERSION }}

      - name: Set GPG_TTY
        run: echo "GPG_TTY=$(tty)" >> $GITHUB_ENV

      - name: Configure GPG Key
        run: |
          mkdir ~/.gnupg/ && chmod 700 ~/.gnupg/ && echo -e "use-agent\npinentry-mode loopback" > ~/.gnupg/gpg.conf
          echo -n "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --no-tty --import

      - name: Deploy to OSSRH and Release to Maven Central
        run: mvn -B --settings .github/settings.xml clean deploy -Drevision=${{ env.RELEASE_VERSION }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
