name: Git tagging

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'The SemVer version number'
        required: true		

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: setup git config
      run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

    - name: commit
      run: |
            git tag v${{ github.event.inputs.VERSION }}
            git push origin v${{ github.event.inputs.VERSION }}
